# Generated by Django 5.1 on 2026-01-12 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0036_remove_order_delivered_and_more'),
        ('users', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='merchSite.product'),
        ),
    ]
