# Generated by Django 5.1 on 2024-08-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discount', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
