# Generated by Django 5.1 on 2024-08-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
