# Generated by Django 5.1 on 2024-08-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
