# Generated by Django 5.1 on 2024-08-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0003_alter_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
