# Generated by Django 5.1 on 2025-02-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0008_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fourth_image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
