# Generated by Django 5.1 on 2025-02-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0009_product_fourth_image_product_second_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
