# Generated by Django 5.1 on 2025-02-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0011_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
