# Generated by Django 5.1 on 2025-07-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0015_billingaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing',
        ),
    ]
