# Generated by Django 5.1 on 2025-07-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0016_remove_order_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
