# Generated by Django 5.1 on 2025-07-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0018_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_options',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
