# Generated by Django 5.1 on 2025-07-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0019_product_size_options_alter_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
