# Generated by Django 5.1 on 2025-07-29 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0022_order_quantity_order_size'),
    ]

    operations = [
        
        migrations.DeleteModel(
            name='ProductVarient',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
