# Generated by Django 5.1 on 2025-07-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0025_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
    ]
