# Generated by Django 5.1 on 2025-07-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0026_rename_status_order_delivered_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
