# Generated by Django 5.1 on 2025-08-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0027_categorie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_available_text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
