# Generated by Django 5.1 on 2025-09-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0028_product_product_available_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
