# Generated by Django 5.1 on 2025-09-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0029_order_is_paid_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
