# Generated by Django 5.1 on 2026-01-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0035_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_other_reason',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reasons',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
