# Generated by Django 5.1 on 2026-01-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0037_returnproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='merchSite.order'),
        ),
    ]
