# Generated by Django 5.1 on 2026-01-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0038_returnproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='quantity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='returnproduct',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
