# Generated by Django 5.1 on 2026-01-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0039_returnproduct_quantity_returnproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproduct',
            name='return_status',
            field=models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Returning', 'Returning'), ('Returned', 'Returned')], default='Pending', max_length=100),
        ),
    ]
