# Generated by Django 5.1 on 2026-01-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0040_alter_returnproduct_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
