# Generated by Django 5.1 on 2026-01-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0041_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_options',
            field=models.JSONField(default={'L': 1, 'M': 1, 'S': 1}),
        ),
    ]
