# Generated by Django 5.1 on 2026-01-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0042_alter_product_size_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivered_date'),
        ),
    ]
