# Generated by Django 5.1 on 2026-01-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0043_order_delivered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('Online Payment', 'Online Payment'), ('Cash On Delivery', 'Cash On Delivery')], null=True),
        ),
    ]
