# Generated by Django 5.1 on 2026-02-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0045_order_cancelled_date_order_returned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='returned_date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
