# Generated by Django 5.1 on 2026-02-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0046_returnproduct_returned_date_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='payment_returned'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_returned',
            field=models.BooleanField(default=False),
        ),
    ]
