# Generated by Django 5.2 on 2026-03-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0047_order_payment_return_date_order_payment_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_available_text',
        ),
    ]
