# Generated by Django 5.1 on 2026-03-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchSite', '0048_remove_product_product_available_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('Online Payment', 'Online Payment'), ('Cash On Delivery', 'Cash On Delivery')], max_length=100, null=True),
        ),
    ]
